name: Build and Publish upon release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and upload to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools and Twine
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Remove old distributions
        run: rm -rf dist/*

      - name: Build the package
        run: python -m build

      - name: Show built files
        run: ls -lh dist/

      - name: Check the package
        run: twine check dist/*

      - name: Publish to PyPI
        run: ${{ secrets.TWINE_UPLOAD }}
